version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    build:
        context: ./filebeat
    container_name: filebeat
    volumes:
        - ./fastapi-logs:/src/logs
    depends_on:
        - elasticsearch
        - kibana

  fastapi:
    build:
      context: ./fastapi-app 
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - elasticsearch
    volumes:
        - ./fastapi-logs:/src/logs

volumes:
    elasticsearch_data:
        driver: local